### ISSUE TITLE
Small issue with installation instructions

### ISSUE THREAD

**Issue by cachapa** [jewel/clearskies#13]
I had a bit of trouble installing Clear Skies on my Debian Unstable and Raspbian distos.

The Ubuntu packages suggested don't seem to exist in Debian, so I tried to use the gem installation method, but that method requires the "ruby-dev" package.
Googling the problem shows that this is also true for Ubuntu, so I propose adding that to the instructions to simplify the installation process for others.

My abridged instructions:
[sudo] apt-get install ruby ruby-dev
[sudo] gem install rb-inotify ffi

**Comment by jewel** [comment]
It looks like Debian unstable has transitioned to naming the packages ruby-rb-inotify and ruby-ffi, and the latest Ubuntu and wheezy still have both the old naming convention and the new one.  I will change the instructions to be the new way, which should cover all cases.
