### ISSUE TITLE
segfault on ARM in debian stable

### ISSUE THREAD

**Issue by jewel** [jewel/clearskies#16]
On a sheevaplug running debian wheezy, the gnutls code segfaults.  I have yet to determine if this is ARM specific.

**Comment by ghost** [comment]
I can test this on armel and armhf if needed.

**Comment by jewel** [comment]
@voltagex It seems to work fine now, I imagine the problem is with the version of `ruby-ffi` in debian stable and is not ARM specific.  If you'd like to test then you can do `ruby test/gnutls.rb`.  I only have a sheevaplug to test on, and @capacha has a pi, so it's possible there are other undiscovered problems on ARM.
