### ISSUE TITLE
ipv6 not working correctly

### ISSUE THREAD

**Issue by larroy** [jewel/clearskies#24]
Looks like host B is trying to connect to an ipv6 port but host A only opened it for ipv4:

HOST A:

tracker> Tracking with http://clearskies.tuxng.com/clearskies/track?id=ab7f710316924fed38f493aa14413442bf2db28c8542054eb50988dc1f596fef%40b44ddbaf4d241e348568a515810654c0&id=10e53688a92370ced39427d8af929217b5445aa40c3cb69c890906231f8bbd33%40b44ddbaf4d241e348568a515810654c0&tcp_port=48555&utp_port=46327

root@cereza:0:/home/piotr/devel/clearskies# lsof -Pni | grep 48555
ruby      19347 piotr    9u  IPv4 1376349      0t0  TCP *:48555 (LISTEN)

HOST B:

tracker> New outgoing connection with A
tracker> Tracker discovered 10e53688a92370ced39427d8af929217b5445aa40c3cb69c890906231f8bbd33 b44ddbaf4d241e348568a515810654c0 utp A 46327
tracker> New outgoing connection with A
connection410> Opening socket to utp A 46327
connection410> Could not connect via utp to 2a02:8109:8440:8b8:f2de:f1ff:fe00:441b:46327: Address family not supported by protocol - sendto(2)
connection409> Opening socket to tcp A 48555
connection409> Could not connect via tcp to A:48555: Connection refused - connect(2)

I can look more into it tomorrow.

**Comment by jewel** [comment]
It looks like if we do:

``` ruby
TCPServer.new 1234
```

Only IPv4 is bound (0.0.0.0), but if we do:

``` ruby
TCPServer.new '::', 1234
```

Then both IPv4 and IPv6 will work.  I'll patch.

Incidentally, it also looks like we're doing something wrong as relates to IPv6 on both ends and uTP.  This isn't a combination I have a test set up for yet.

**Comment by jewel** [comment]
I believe this is fixed in 9c2f49bbc5.  My only concern is that it might break hosts that are IPv4 only, meaning they don't even have IPv6 enabled in the kernel.

**Comment by jewel** [comment]
Oops, meant to leave this open so that you could close it, @larroy, if it's really fixed.

**Comment by jewel** [comment]
I've opened a separate issue, #25, for the uTP issue I noticed from your log.

**Comment by jewel** [comment]
I believe this has been fixed.
