### ISSUE TITLE
[feature] support time difference accounting in peers to make it more robust

### ISSUE THREAD

**Issue by larroy** [jewel/clearskies#26]
It's a bit of a hassle to assume that all peers need to have the clocks synchronized.

**Comment by jewel** [comment]
It is a pain, but I'm not sure of a good way around it.  If we can find one, then we can update the spec and make it a requirement.

One particular situation to watch out for is three-way sync.  We want to guarantee eventual consistency across all three machines.  If adjustments are being made to the incoming timestamps, can we guarantee that the [tree merge algorithm](https://github.com/jewel/clearskies/blob/master/protocol/core.md#tree-merge-algorithm) will give the same result on each machine?

**Comment by jewel** [comment]
This has been addressed at the protocol level by switching to a causality-violation tracking mechanism.  (Currently ITCs but it might be switched to vector clocks.)
