### ISSUE TITLE
Daemon not starting after recent commit

### ISSUE THREAD

**Issue by cachapa** [jewel/clearskies#27]
Commit 9c2f4 (Bind TCP to IPv6) broke one of my Clearskies setups: Raspberry Pi on IPv4-only network.
My other setup on a desktop in a dual IPv4+IPv6 network works fine, so I can't say if the problem is the architecture of the network.

The previous commit runs fine.
Here's the error log.

12:35:21.287118246 error main> Exiting due to exception in 'main' thread: Address family not supported by protocol - socket(2)
12:35:21.287557228 error main> /home/cachapa/clearskies/lib/network.rb:20:in `initialize'
12:35:21.287898214 error main> /home/cachapa/clearskies/lib/network.rb:20:in`new'
12:35:21.288262200 error main> /home/cachapa/clearskies/lib/network.rb:20:in `start'
12:35:21.288597186 error main> /home/cachapa/clearskies/lib/daemon.rb:62:in`run'
12:35:21.288930173 error main> /home/cachapa/clearskies/lib/daemon.rb:41:in `daemonize'
12:35:21.289513149 error main> ./clearskies:147:in`<main>'

**Comment by jewel** [comment]
I'm sorry about that.  I thought that the change might cause problems, but wasn't able to find an easy way to test it.  My network at home is also IPv4 only, but it doesn't have the problem.  I think based on the `ip addr` output that you sent me that the raspberry pi doesn't have IPv6 enabled in the kernel.  In any case, I'll fix the issue by trying IPv6 and then falling back to IPv4 if it fails.

**Comment by cachapa** [comment]
That's what I thought.
If it helps, I can create a login for you in the RPi so you can test things yourself.

**Comment by jewel** [comment]
Should be fixed by 3702872.  I'm looking into setting up a way to do automated testing with vagrant where we can test the full range of connection types, but if that fails me then getting a login will be really helpful.

**Comment by cachapa** [comment]
Sounds good.
Let me know if/when you need one.

I'm closing this bug as the fix worked (clearskies starts now).

However, it's still not synching with my home server due to my RPi not being able to speak IPv6 (same "address family not supported by protocol" log message). There are already two IPv6-related issues open, so it makes no sense to track it as well here.
