### ISSUE TITLE
Cannot load GNUTLS (Windows)

### ISSUE THREAD

**Issue by chid** [jewel/clearskies#33]
I was wondering how to get this section loaded on windows, I have tried installing gnutls (libgnutls26) with cygwin, have I missed anything?

https://github.com/jewel/clearskies/blob/master/lib/gnutls.rb

**Comment by willemt** [comment]
I tried this the other day. You need to add "libgnutls-28" to the following code in gnutls.rb:

``` ruby
  loaded = false
  %w{gnutls libgnutls-28 gnutls.so.26 gnutls.so.28}.each do |lib|
    begin
      ffi_lib lib
```

I also put libgnutls-28.dll in the clearskies top level folder. Hope it helps

**Comment by chid** [comment]
Thanks, didn't work for me though, I tried placing them in the system32 folder, and I also tried libgnutls-26.dll

**Comment by jewel** [comment]
@willemt, were you using cygwin as well?  I imagine it will work with a cygwin ruby and cygwin gnutls, or a native ruby and native gnutls, but not both.

**Comment by willemt** [comment]
No, I was using mingw instead

**Comment by jewel** [comment]
@chid if you get a chance, do you want to try using a mingw gnutls DLL insetad of cygwin to see if it works?

I'm going to close this issue since the ruby implementation is now in its own repository, but please open an issue in that repository if the mingw version doesn't work.
