### ISSUE TITLE
separate implementation and protocol in different repositories

### ISSUE THREAD

**Issue by larroy** [jewel/clearskies#42]
Hi

as agreed we should separate the protocol spec and implementation in different repositories.

**Comment by GitMoDu** [comment]
A lesson hard learned from the codec world is to never conflate the two!
Kudos Larroy, keep it up.

2014-03-24 15:00 GMT+00:00 Pedro Larroy notifications@github.com:

**Comment by jewel** [comment]
https://github.com/jewel/clearskies-ruby
