### ISSUE TITLE
No fork in JRuby

### ISSUE THREAD

**Issue by onionjake** [jewel/clearskies#8]
The following test cases fail because there is no fork in Jruby.

  1) Error:
test_0001_can_connect_and_send_data(GnuTLS::Session::acts as a client):
NotImplementedError: fork is not available on this platform
    org/jruby/RubyKernel.java:1855:in `fork'
    clearskies/test/gnutls.rb:16:in`run_test'
    org/jruby/RubyBasicObject.java:1735:in `instance_eval'

  2) Error:
test_0002_won_t_connect_with_wrong_password(GnuTLS::Session::acts as a client):
NotImplementedError: fork is not available on this platform
    org/jruby/RubyKernel.java:1855:in `fork'
    clearskies/test/gnutls.rb:16:in`run_test'
    org/jruby/RubyBasicObject.java:1735:in `instance_eval'

  3) Error:
test_0001_can_connect_and_send_data(GnuTLS::Session::acts as a server):
NotImplementedError: fork is not available on this platform
    org/jruby/RubyKernel.java:1855:in `fork'
    clearskies/test/gnutls.rb:16:in`run_test'
    org/jruby/RubyBasicObject.java:1735:in `instance_eval'

  4) Error:
test_0002_won_t_connect_with_wrong_password(GnuTLS::Session::acts as a server):
NotImplementedError: fork is not available on this platform
    org/jruby/RubyKernel.java:1855:in `fork'
    clearskies/test/gnutls.rb:16:in`run_test'
    org/jruby/RubyBasicObject.java:1735:in `instance_eval'

**Comment by jewel** [comment]
At one point we were using threads.  We can spawn a separate process for the test servers, or we can fall back to threads.  For now we should just skip those tests.

**Comment by onionjake** [comment]
Closing as we do not really advertise that we work on JRuby.
