### ISSUE TITLE
Die properly if two instances are ran

### ISSUE THREAD

**Issue by onionjake** [jewel/clearskies#9]
If you run two clearskies instances you get a crashed thread, but clearskies continues to run.  It should exit.

control> Thread crash: Daemon already running
control> /home/jake/repos/clearskies/lib/control_server.rb:23:in `run'
control> /home/jake/repos/clearskies/lib/control_server.rb:13:in`block in start'
control> /home/jake/repos/clearskies/lib/simple_thread.rb:72:in `block (2 levels) in initialize'
control> /home/jake/repos/clearskies/lib/simple_thread.rb:38:in`glock'
control> /home/jake/repos/clearskies/lib/simple_thread.rb:70:in `block in initialize'

**Comment by jewel** [comment]
This was fixed in cd483e6312e1d8193e30e8efb6ab313d730d429d.
